#!/usr/bin/env python3
"""
PTE Real-Time Availability Simulator (synthetic Hobart CBD fixture)
===================================================================

WHY THIS EXISTS
---------------
Parking Truth Engine needs to prove that a *live* availability feed, a moving
GPS position, and the frontend contract all work together BEFORE any real
municipal feed is legally wired up.

Real Hobart feeds exist (Park My Ride / parking-occupancy.hobartcity.com.au)
but they are:
  * not published as a documented public API,
  * behind bot protection (parkmyride.au -> Azure Front Door WAF), and
  * explicitly "may not reuse or republish ... without written consent from
    the City" (hobartcity.com.au Live parking availability map page).

So this simulator emits a feed with the SAME SHAPE, CADENCE and FAILURE MODES
as a real sensor network, using geometry that is clearly labelled SYNTHETIC.
Nothing here is authoritative and nothing here may be presented as real Hobart
occupancy.

WHAT IT EMITS
-------------
  GET /api/health            source-health record (PTE shape: FRESH/STALE/...)
  GET /api/carparks.json     off-street occupancy (real capacities, synthetic counts)
  GET /api/bays.geojson      on-street bays + live status (GeoJSON FeatureCollection)
  GET /api/snapshot.json     compact combined snapshot, one HTTP round trip
  GET /api/bay/<bay_id>      single bay detail incl. occupiedSince
  GET /stream                Server-Sent Events: arrival/departure ticks
  GET /api/meta.json         simulator config + provenance/disclaimer

Cadence defaults to a 15 s tick, matching the published Park My Ride sensor
refresh rate. Use --tick for other cadences and --speed to run simulated time
faster than wall-clock.

STDLIB ONLY. Python 3.8+. No dependencies to install.

    python3 sim_feed.py                       # 0.0.0.0:8090, 15 s tick
    python3 sim_feed.py --port 8080 --speed 20
    python3 sim_feed.py --tick 5 --seed 42
"""

from __future__ import annotations

import argparse
import json
import math
import os
import random
import threading
import time
from datetime import datetime, timezone, timedelta
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

# --------------------------------------------------------------------------- #
# Provenance constants
# --------------------------------------------------------------------------- #

SIMULATOR_ID = "pte-sim-hobart-cbd"
DISCLAIMER = (
    "SYNTHETIC SIMULATOR OUTPUT. NOT REAL PARKING DATA. Bay IDs, coordinates, "
    "occupancy counts and events are generated by tools/realtime-sim/sim_feed.py "
    "for pipeline testing only. Street geometry is an approximate hand-authored "
    "skeleton of the Hobart CBD and is NOT authoritative. Do not display to end "
    "users as real availability. See docs/HOBART-AVAILABILITY-SOURCE-PREFLIGHT.md."
)

# Hobart is AEST (UTC+10) year-round; Tasmania observes DST (AEDT, UTC+11) in
# summer. PTE core handles IANA timezones; the simulator stays on a fixed
# offset and records it so tests are deterministic.
HOBART_TZ_NAME = "Australia/Hobart"

# Off-street capacities are the figures published by the City of Hobart in its
# 1 Sep 2025 "Park smarter, not harder" media release. Capacities are REAL and
# cited; the occupancy numbers are SYNTHETIC.
CARPARKS = [
    # key, name, capacity, approx lat, approx lon
    ("argyle",     "Argyle Street Car Park",   1133, -42.87960, 147.32780),
    ("centrepoint","Centrepoint Car Park",      782, -42.88330, 147.32660),
    ("central",    "Hobart Central Car Park",   462, -42.88160, 147.32570),
    ("condell",    "Condell Place Car Park",     83, -42.88100, 147.32900),
    ("dunn",       "Dunn Place Car Park",        82, -42.88260, 147.32950),
    ("lefroy",     "Lefroy Street Car Park",     47, -42.87900, 147.32350),
]

# Approximate hand-authored CBD street skeleton. NOT survey data.
# Each street is a polyline of (lat, lon) vertices.
STREETS = {
    "Elizabeth St":   [(-42.87750, 147.32550), (-42.88300, 147.32630), (-42.88850, 147.32750)],
    "Liverpool St":   [(-42.87900, 147.32350), (-42.88350, 147.32430), (-42.88800, 147.32500)],
    "Argyle St":      [(-42.87800, 147.32800), (-42.88350, 147.32880), (-42.88900, 147.32950)],
    "Campbell St":    [(-42.88000, 147.32950), (-42.88400, 147.33020), (-42.88800, 147.33100)],
    "Harrington St":  [(-42.87950, 147.32650), (-42.88300, 147.32700)],
    "Bathurst St":    [(-42.88000, 147.32300), (-42.88040, 147.32650), (-42.88080, 147.33000)],
    "Collins St":     [(-42.88380, 147.32180), (-42.88430, 147.32600), (-42.88480, 147.33000)],
    "Murray St":      [(-42.88300, 147.32220), (-42.88340, 147.32640), (-42.88380, 147.33050)],
    "Macquarie St":   [(-42.88480, 147.32150), (-42.88530, 147.32570), (-42.88580, 147.32980)],
    "Davey St":       [(-42.88620, 147.32250), (-42.88660, 147.32630), (-42.88700, 147.33000)],
    "Salamanca Pl":   [(-42.88680, 147.32880), (-42.88770, 147.32940), (-42.88850, 147.33000)],
    "Morrison St":    [(-42.88780, 147.32820), (-42.88830, 147.32900)],
}

# Precincts drive the demand curve. Salamanca saturates on Saturday market day.
PRECINCTS = {
    "Elizabeth St":  "cbd-core",
    "Liverpool St":  "cbd-core",
    "Argyle St":     "cbd-core",
    "Campbell St":   "cbd-east",
    "Harrington St": "cbd-north",
    "Bathurst St":   "cbd-north",
    "Collins St":    "cbd-core",
    "Murray St":     "cbd-core",
    "Macquarie St":  "cbd-south",
    "Davey St":      "cbd-south",
    "Salamanca Pl":  "salamanca",
    "Morrison St":   "salamanca",
}

# Restriction classes. Mirrors the vocabulary a legality kernel would emit; the
# simulator deliberately does NOT decide legality, it only labels what a bay is.
RESTRICTIONS = ["P1", "P2", "P3", "P4", "METER_1P", "METER_2P", "LOADING_30M",
                "PERMIT_RESIDENT", "DISABLED", "NO_PARKING", "UNRESTRICTED"]
RESTRICTION_WEIGHTS = [8, 14, 10, 4, 10, 12, 3, 4, 2, 3, 6]

BAY_SPACING_M = 6.2          # typical parallel bay length incl. gap
BAYS_PER_BLOCK_RANGE = (6, 22)

# Demand curve: fraction of the precinct's legal, sensable bays that would be
# occupied at equilibrium, by hour of day (Hobart local). Two peaks: commuter
# arrival ~08:30 and retail/lunch ~12:30, tapering after 18:00.
BASE_CURVE = [
    (0, 0.06), (2, 0.04), (4, 0.04), (6, 0.10), (7, 0.24), (8, 0.48),
    (9, 0.66), (10, 0.78), (11, 0.86), (12, 0.92), (13, 0.94), (14, 0.88),
    (15, 0.82), (16, 0.80), (17, 0.74), (18, 0.60), (19, 0.48), (20, 0.40),
    (21, 0.32), (22, 0.22), (23, 0.12),
]

# Mean parking duration in minutes by restriction class. Drives departure rate.
MEAN_STAY_MIN = {
    "P1": 45, "P2": 105, "P3": 170, "P4": 245,
    "METER_1P": 52, "METER_2P": 98, "LOADING_30M": 16,
    "PERMIT_RESIDENT": 640, "DISABLED": 130, "NO_PARKING": 0, "UNRESTRICTED": 380,
}

# Precinct multipliers and the Saturday Salamanca market spike.
PRECINCT_PEAK_MULT = {"cbd-core": 1.00, "cbd-east": 0.86, "cbd-north": 0.80,
                      "cbd-south": 0.90, "salamanca": 0.94}

STATUS_FREE, STATUS_OCCUPIED, STATUS_RESTRICTED, STATUS_UNKNOWN = (
    "FREE", "OCCUPIED", "RESTRICTED", "UNKNOWN")


def interp_curve24(curve, hour_float):
    """Linear interpolation over a 24-value hourly curve, wrapping midnight."""
    if not curve or len(curve) != 24:
        return None
    h = hour_float % 24.0
    lo = int(h) % 24
    hi = (lo + 1) % 24
    frac = h - int(h)
    return curve[lo] + (curve[hi] - curve[lo]) * frac


def sample_inverse_cdf(inv_cdf, rng):
    """Inverse-transform sample from an empirical percentile table."""
    if not inv_cdf:
        return None
    u = rng.random()
    pts = sorted(((float(k["q"]), float(k["seconds"]))
                  for k in inv_cdf if k.get("seconds") is not None))
    if not pts:
        return None
    if u <= pts[0][0]:
        return max(60.0, pts[0][1])
    if u >= pts[-1][0]:
        return max(60.0, pts[-1][1])
    for (q0, s0), (q1, s1) in zip(pts, pts[1:]):
        if q0 <= u <= q1:
            span = (q1 - q0) or 1e-9
            return max(60.0, s0 + (s1 - s0) * ((u - q0) / span))
    return max(60.0, pts[-1][1])


def target_occupancy(precinct: str, hour_float: float, weekday: int, cal=None) -> float:
    """Equilibrium occupancy fraction for a precinct at a given local time.

    When a calibration derived from REAL parking-event data is supplied, the
    hourly curve comes from Little's Law over that archive (see
    tools/telemetry/calibrate_sim.py) instead of the hand-written BASE_CURVE
    below. Weekend/market adjustments are still applied on top, because the
    archive is city-wide and does not model this simulator's precincts.
    """
    if cal:
        curve = cal.get("occupancyCurveByHour")
        measured = interp_curve24(curve, hour_float)
        if measured is not None:
            base = measured * PRECINCT_PEAK_MULT.get(precinct, 0.9)
            if precinct == "salamanca" and weekday == 5 and 8.0 <= hour_float <= 15.0:
                base = min(0.995, base + 0.34)
            if weekday >= 5 and precinct.startswith("cbd"):
                base *= 0.72
            return max(0.0, min(0.995, base))
        # calibration present but unusable -> fall through to the built-in curve

    pts = BASE_CURVE
    lo = pts[-1]
    hi = pts[0]
    for i in range(len(pts) - 1):
        if pts[i][0] <= hour_float < pts[i + 1][0]:
            lo, hi = pts[i], pts[i + 1]
            break
    else:
        lo, hi = pts[-1], (24, pts[0][1])
    span = (hi[0] - lo[0]) or 1
    frac = (hour_float - lo[0]) / span
    base = lo[1] + (hi[1] - lo[1]) * frac

    base *= PRECINCT_PEAK_MULT.get(precinct, 0.9)

    # Saturday 08:00-15:00 Salamanca Market saturation. weekday: Mon=0..Sun=6
    if precinct == "salamanca" and weekday == 5 and 8.0 <= hour_float <= 15.0:
        base = min(0.995, base + 0.34)
    # Weekends are generally quieter in the CBD core.
    if weekday >= 5 and precinct.startswith("cbd"):
        base *= 0.72

    return max(0.0, min(0.995, base))


class Bay:
    __slots__ = ("bay_id", "street", "precinct", "lat", "lon", "restriction",
                 "sensable", "status", "occupied_since", "stay_target_s",
                 "sensor_ok", "last_event_seq", "cal")

    def __init__(self, bay_id, street, precinct, lat, lon, restriction, sensable,
                 rng, cal=None):
        self.bay_id = bay_id
        self.street = street
        self.precinct = precinct
        self.lat = lat
        self.lon = lon
        self.restriction = restriction
        self.sensable = sensable
        self.status = STATUS_UNKNOWN if not sensable else STATUS_FREE
        self.occupied_since = None
        self.stay_target_s = 0
        self.sensor_ok = True
        self.last_event_seq = 0
        self.cal = cal
        if sensable:
            self.stay_target_s = self._draw_stay(rng)

    def _draw_stay(self, rng):
        """Draw a parking duration in seconds.

        Lognormal, median = 70% of the class mean stay, sigma 0.62 so the tail
        deliberately crosses signposted time limits. That matters: an
        `overstayed` flag lets a test assert the UI shows overstay risk WITHOUT
        the availability lane being allowed to conclude anything about legality.
        """
        mean_min = MEAN_STAY_MIN.get(self.restriction, 120) or 120

        # Prefer the MEASURED distribution from real parking-event data.
        # Scale it per restriction class so a 1P bay still stays short and a
        # residential-permit bay still stays long, while the overall shape comes
        # from observation rather than from an invented lognormal.
        if self.cal:
            inv = (self.cal.get("stayDurationSeconds") or {}).get("inverseCdf")
            secs = sample_inverse_cdf(inv, rng)
            if secs:
                cal_median_min = ((self.cal.get("stayDurationSeconds") or {})
                                  .get("medianMinutes")) or 0
                if cal_median_min and cal_median_min > 0:
                    secs *= (mean_min / cal_median_min)
                return max(90.0, min(secs, 26 * 3600))

        secs = rng.lognormvariate(math.log(mean_min * 60 * 0.70), 0.62)
        return max(90.0, min(secs, 26 * 3600))

    def is_overstayed(self, now_epoch):
        if self.status != STATUS_OCCUPIED or not self.occupied_since:
            return False
        limit_min = {"P1": 60, "P2": 120, "P3": 180, "P4": 240,
                     "METER_1P": 60, "METER_2P": 120, "LOADING_30M": 30,
                     "DISABLED": 120}.get(self.restriction)
        if limit_min is None:
            return False
        return (now_epoch - self.occupied_since) > limit_min * 60


def haversine_m(a_lat, a_lon, b_lat, b_lon):
    r = 6371000.0
    p1, p2 = math.radians(a_lat), math.radians(b_lat)
    dp = math.radians(b_lat - a_lat)
    dl = math.radians(b_lon - a_lon)
    h = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * r * math.asin(math.sqrt(h))


class World:
    """Holds bay/car-park state and advances it one tick at a time."""

    def __init__(self, seed=1337, sim_start=None, bays_per_block=None,
                 calibration=None):
        self.rng = random.Random(seed)
        self.seed = seed
        self.cal = calibration if (calibration and calibration.get("usable")) else None
        self._restriction_pool = None
        self._restriction_weights = None
        if self.cal and self.cal.get("restrictionMix"):
            mix = self.cal["restrictionMix"]
            self._restriction_pool = list(mix.keys())
            self._restriction_weights = [max(1e-6, float(v)) for v in mix.values()]
        self.lock = threading.Lock()
        self.seq = 0
        self.tick_count = 0
        self.sim_epoch = sim_start if sim_start is not None else time.time()
        self.started_wall = time.time()
        self.events = []          # rolling buffer, bounded
        self.events_max = 500
        self.bays = []
        self.carparks = []
        self._build_bays(bays_per_block)
        self._build_carparks()
        self._seed_equilibrium()

    def _seed_equilibrium(self):
        """Start sensable bays at the target occupancy for the start hour.

        Without this, every run begins all-FREE and spends the first simulated
        hour ramping toward the measured curve, so short test runs would report
        occupancy that reflects the ramp rather than the calibration.
        """
        d = self.dt_local()
        for b in self.bays:
            if not b.sensable or b.restriction == "NO_PARKING":
                continue
            rho = target_occupancy(b.precinct, d.hour_float, d.weekday, self.cal)
            if self.rng.random() < rho:
                b.status = STATUS_OCCUPIED
                # backdate within the stay so departures begin immediately
                back = self.rng.random() * (b.stay_target_s or 600.0)
                b.occupied_since = self.sim_epoch - back

    # ---------------------------------------------------------------- build --
    def _build_bays(self, bays_per_block):
        n = 0
        for street, verts in STREETS.items():
            precinct = PRECINCTS.get(street, "cbd-core")
            for seg in range(len(verts) - 1):
                a, b = verts[seg], verts[seg + 1]
                seg_len = haversine_m(a[0], a[1], b[0], b[1])
                lo, hi = bays_per_block or BAYS_PER_BLOCK_RANGE
                count = max(2, int(seg_len / BAY_SPACING_M))
                count = min(count, self.rng.randint(lo, hi) + 8)
                for side in (0, 1):
                    for i in range(count):
                        t = (i + 0.5) / count
                        lat = a[0] + (b[0] - a[0]) * t
                        lon = a[1] + (b[1] - a[1]) * t
                        # offset the two "sides" of the street ~4 m apart
                        off = 0.000036 if side == 0 else -0.000036
                        lat += off
                        lon += off * 0.6
                        if self._restriction_pool:
                            restriction = self.rng.choices(
                                self._restriction_pool,
                                weights=self._restriction_weights)[0]
                        else:
                            restriction = self.rng.choices(
                                RESTRICTIONS, weights=RESTRICTION_WEIGHTS)[0]
                        sensable = restriction != "NO_PARKING" and self.rng.random() < 0.88
                        n += 1
                        self.bays.append(Bay(
                            bay_id=f"SIM-HBT-{n:05d}", street=street,
                            precinct=precinct, lat=round(lat, 6),
                            lon=round(lon, 6), restriction=restriction,
                            sensable=sensable, rng=self.rng, cal=self.cal))
        self.bay_index = {b.bay_id: b for b in self.bays}

    def _build_carparks(self):
        for key, name, cap, lat, lon in CARPARKS:
            self.carparks.append({
                "carparkId": f"SIM-CP-{key.upper()}",
                "name": name,
                "capacity": cap,
                "lat": lat, "lon": lon,
                "occupied": int(cap * self.rng.uniform(0.05, 0.4)),
                "lastUpdate": self.sim_epoch,
            })
        self.carpark_index = {c["carparkId"]: c for c in self.carparks}

    # ----------------------------------------------------------------- time --
    def local_dt(self):
        """Simulator local time. Fixed UTC+10 for determinism (see module doc)."""
        return datetime.fromtimestamp(self.sim_epoch, tz=timezone(timedelta(hours=10)))

    # ----------------------------------------------------------------- tick --
    def tick(self, dt_sim_seconds):
        self.sim_epoch += dt_sim_seconds
        self.tick_count += 1
        dt = self.dt_local()
        produced = []

        with self.lock:
            # --- on-street bays ------------------------------------------- #
            sensable_by_precinct = {}
            for b in self.bays:
                if not b.sensable:
                    continue
                sensable_by_precinct[b.precinct] = sensable_by_precinct.get(b.precinct, 0) + 1

            targets = {p: target_occupancy(p, dt.hour_float, dt.weekday, self.cal)
                       for p in sensable_by_precinct}

            # --- arrival hazard derived from the departure hazard ----------- #
            # Each occupied bay leaves as a Poisson process with rate
            #     mu = 1 / stay_target_s
            # For the precinct to sit at the target occupancy rho in
            # equilibrium, arrivals onto FREE bays must balance departures:
            #     lambda * (1 - rho) = mu_bar * rho
            #     lambda = mu_bar * rho / (1 - rho)
            # This is the same identity that produced rho (Little's Law), so the
            # simulator converges to the MEASURED curve at any tick size instead
            # of overshooting it. Per-tick probabilities are then the exact
            # exponential-hazard forms, which stay correct for large dt.
            mu_sum = {}
            for b in self.bays:
                if b.sensable and b.sensor_ok and b.restriction != "NO_PARKING":
                    mu_sum[b.precinct] = mu_sum.get(b.precinct, 0.0) + \
                        (1.0 / (b.stay_target_s or 600.0))
            lam_by_precinct = {}
            for p, cap in sensable_by_precinct.items():
                rho = min(0.995, max(0.0, targets.get(p, 0.5)))
                mu_bar = (mu_sum.get(p, 0.0) / cap) if cap else (1.0 / 600.0)
                lam_by_precinct[p] = mu_bar * rho / max(1e-6, 1.0 - rho)

            for b in self.bays:
                # Signage-known "no parking" bays carry no sensor at all, but
                # their status is still KNOWN-restricted from inventory. This
                # is an inventory fact, NOT a legality verdict - see meta().
                if b.restriction == "NO_PARKING":
                    b.status = STATUS_RESTRICTED
                    continue
                if not b.sensable:
                    # No sensor coverage -> UNKNOWN. Never inferred FREE.
                    b.status = STATUS_UNKNOWN
                    continue
                if not b.sensor_ok:
                    # Sensor present but faulted -> UNKNOWN, not a guess.
                    b.status = STATUS_UNKNOWN
                    continue

                if b.status == STATUS_OCCUPIED:
                    mean = b.stay_target_s or 600
                    p_leave = 1.0 - math.exp(-dt_sim_seconds / mean)
                    if self.rng.random() < p_leave:
                        b.status = STATUS_FREE
                        dur = int(self.sim_epoch - (b.occupied_since or self.sim_epoch))
                        b.occupied_since = None
                        b.stay_target_s = b._draw_stay(self.rng)
                        produced.append(self._event("departure", b, {"staySeconds": dur}))
                else:
                    lam = lam_by_precinct.get(b.precinct, 1.0 / 600.0)
                    p_arrive = 1.0 - math.exp(-lam * dt_sim_seconds)
                    if self.rng.random() < p_arrive:
                        b.status = STATUS_OCCUPIED
                        b.occupied_since = self.sim_epoch
                        produced.append(self._event("arrival", b, {}))

            # --- sensor faults: rare, and they must surface as UNKNOWN ------ #
            if self.rng.random() < 0.02:
                victim = self.rng.choice(self.bays)
                if victim.sensable:
                    victim.sensor_ok = not victim.sensor_ok
                    victim.status = STATUS_UNKNOWN if not victim.sensor_ok else STATUS_FREE
                    produced.append(self._event(
                        "sensor_fault" if not victim.sensor_ok else "sensor_recovered",
                        victim, {}))

            # --- off-street car parks -------------------------------------- #
            for c in self.carparks:
                cap = c["capacity"]

                # Feed dropout: a real car-park counter feed goes silent now and
                # then. While stale we must NOT update lastUpdate, so the
                # availability lane can legitimately fall through to UNKNOWN
                # instead of serving a confident-but-old number.
                stale_until = c.get("staleUntil") or 0
                if self.sim_epoch < stale_until:
                    continue
                if self.rng.random() < 0.004:
                    c["staleUntil"] = self.sim_epoch + self.rng.uniform(180, 900)
                    continue

                hour_frac = dt.hour_float
                base = target_occupancy("cbd-core", hour_frac, dt.weekday, self.cal)
                want = int(cap * min(0.985, base * self.rng.uniform(0.88, 1.04)))
                delta = want - c["occupied"]
                if delta != 0:
                    move = int(round(delta * min(1.0, dt_sim_seconds / 900.0)))
                    if move == 0:
                        move = 1 if delta > 0 else -1
                    c["occupied"] = max(0, min(cap, c["occupied"] + move))
                c["lastUpdate"] = self.sim_epoch

            self.seq += 1
            for e in produced:
                e["seq"] = self.seq
            self.events.extend(produced)
            if len(self.events) > self.events_max:
                del self.events[: len(self.events) - self.events_max]

        return produced

    def _event(self, kind, bay, extra):
        rec = {
            "type": kind,
            "bayId": bay.bay_id,
            "street": bay.street,
            "precinct": bay.precinct,
            "restriction": bay.restriction,
            "lat": bay.lat, "lon": bay.lon,
            "observedAt": iso(self.sim_epoch),
            "simTick": self.tick_count,
            "simulator": SIMULATOR_ID,
            "synthetic": True,
        }
        rec.update(extra)
        return rec

    # --------------------------------------------------------------- reads --
    def source_health(self):
        with self.lock:
            total = len(self.bays)
            sensable = sum(1 for b in self.bays if b.sensable)
            faulted = sum(1 for b in self.bays if b.sensable and not b.sensor_ok)
            unknown = sum(1 for b in self.bays if b.status == STATUS_UNKNOWN)
            restricted = sum(1 for b in self.bays if b.status == STATUS_RESTRICTED)
            occupied = sum(1 for b in self.bays if b.status == STATUS_OCCUPIED)
        coverage = sensable / total if total else 0.0
        fault_rate = faulted / sensable if sensable else 0.0
        if coverage < 0.5:
            state = "DEGRADED"
        elif fault_rate > 0.15:
            state = "DEGRADED"
        else:
            state = "FRESH"
        return {
            "sourceId": SIMULATOR_ID,
            "state": state,
            "synthetic": True,
            "checkedAt": iso(time.time()),
            "simulatedAt": iso(self.sim_epoch),
            "tickCount": self.tick_count,
            "lastEventSeq": self.seq,
            "metrics": {
                "totalBays": total,
                "sensableBays": sensable,
                "sensorCoverage": round(coverage, 4),
                "faultedSensors": faulted,
                "faultRate": round(fault_rate, 4),
                "occupiedBays": occupied,
                "unknownStatusBays": unknown,
                "restrictedBays": restricted,
                "carparks": len(self.carparks),
            },
            "notes": "Simulated source-health. Demonstrates DEGRADED transitions "
                     "when sensor coverage or fault rate crosses thresholds.",
            "separationNote": "Availability lane only. Nothing in this payload "
                              "is a legality verdict. `restriction` is inventory "
                              "metadata and must not be treated as ALLOWED / "
                              "PROHIBITED by a consumer; legality comes from the "
                              "rule kernel.",
            "disclaimer": DISCLAIMER,
        }

    def dt_local(self):
        d = self.local_dt()
        return type("DT", (), {
            "hour_float": d.hour + d.minute / 60.0 + d.second / 3600.0,
            "weekday": d.weekday(),
            "dt": d,
        })()

    def bays_geojson(self):
        with self.lock:
            feats = []
            for b in self.bays:
                feats.append({
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [b.lon, b.lat]},
                    "properties": {
                        "bayId": b.bay_id,
                        "street": b.street,
                        "precinct": b.precinct,
                        "restriction": b.restriction,
                        "sensable": b.sensable,
                        "sensorOk": b.sensor_ok,
                        "status": b.status,
                        "occupiedSince": iso(b.occupied_since) if b.occupied_since else None,
                        "overstayed": b.is_overstayed(self.sim_epoch),
                        "observedAt": iso(self.sim_epoch),
                        "synthetic": True,
                        "geometryAuthority": "SYNTHETIC-APPROXIMATE (not surveyed)",
                    },
                })
        return {
            "type": "FeatureCollection",
            "generatedAt": iso(self.sim_epoch),
            "simulator": SIMULATOR_ID,
            "count": len(feats),
            "disclaimer": DISCLAIMER,
            "features": feats,
        }

    def carparks_json(self):
        """Off-street occupancy.

        `availability` uses only the three states in the PTE frontend contract:
        HIGH / LIMITED / UNKNOWN. UNKNOWN is reached when the counter feed has
        gone stale, never as a synonym for "full".
        """
        with self.lock:
            now = self.sim_epoch
            out = []
            for c in self.carparks:
                occ, cap = c["occupied"], c["capacity"]
                age = now - c["lastUpdate"]
                stale = age > max(180.0, CONFIG["tick"] * 12)
                ratio = occ / cap if cap else 0.0
                if stale:
                    availability = "UNKNOWN"
                elif ratio < 0.60:
                    availability = "HIGH"
                else:
                    availability = "LIMITED"
                out.append({
                    "carparkId": c["carparkId"],
                    "name": c["name"],
                    "capacity": cap,
                    "occupied": occ,
                    "available": cap - occ,
                    "occupancyRatio": round(ratio, 4),
                    "nearFull": ratio >= 0.90,
                    "availability": availability,
                    "lastUpdate": iso(c["lastUpdate"]),
                    "ageSeconds": round(age, 1),
                    "stale": stale,
                    "synthetic": True,
                })
        return {"generatedAt": iso(self.sim_epoch), "carparks": out,
                "disclaimer": DISCLAIMER,
                "capacitySource": "City of Hobart media release, 2025-09-01 "
                                  "(capacities are real/cited; counts are synthetic)"}

    def snapshot(self):
        with self.lock:
            free = sum(1 for b in self.bays if b.status == STATUS_FREE)
            occ = sum(1 for b in self.bays if b.status == STATUS_OCCUPIED)
            unk = sum(1 for b in self.bays if b.status == STATUS_UNKNOWN)
            res = sum(1 for b in self.bays if b.status == STATUS_RESTRICTED)
            over = sum(1 for b in self.bays if b.is_overstayed(self.sim_epoch))
            by_street = {}
            for b in self.bays:
                s = by_street.setdefault(b.street, {"free": 0, "occupied": 0,
                                                    "unknown": 0, "total": 0})
                s["total"] += 1
                if b.status == STATUS_FREE: s["free"] += 1
                elif b.status == STATUS_OCCUPIED: s["occupied"] += 1
                else: s["unknown"] += 1
        return {
            "generatedAt": iso(self.sim_epoch),
            "simulator": SIMULATOR_ID,
            "synthetic": True,
            "onStreet": {"total": len(self.bays), "free": free, "occupied": occ,
                         "unknown": unk, "restricted": res, "overstayed": over,
                         "byStreet": by_street},
            "offStreet": [{"carparkId": c["carparkId"], "name": c["name"],
                           "capacity": c["capacity"], "occupied": c["occupied"],
                           "available": c["capacity"] - c["occupied"]}
                          for c in self.carparks],
            "recentEvents": self.events[-40:],
            "disclaimer": DISCLAIMER,
        }

    def bay_detail(self, bay_id):
        with self.lock:
            b = self.bay_index.get(bay_id)
            if not b:
                return None
            return {
                "bayId": b.bay_id, "street": b.street, "precinct": b.precinct,
                "lat": b.lat, "lon": b.lon, "restriction": b.restriction,
                "sensable": b.sensable, "sensorOk": b.sensor_ok,
                "status": b.status,
                "occupiedSince": iso(b.occupied_since) if b.occupied_since else None,
                "overstayed": b.is_overstayed(self.sim_epoch),
                "observedAt": iso(self.sim_epoch),
                "synthetic": True,
                "disclaimer": DISCLAIMER,
            }

    def meta(self):
        cal_prov = None
        if self.cal:
            p = self.cal.get("provenance", {})
            cal_prov = {
                "calibrated": True,
                "label": self.cal.get("label"),
                "method": (self.cal.get("method") or {}).get("occupancyCurve"),
                "sourceSha256": p.get("sourceSha256"),
                "sourceUrl": p.get("sourceUrl"),
                "rowsRead": p.get("rowsRead"),
                "distinctBays": p.get("distinctBays"),
                "medianStayMinutes": (self.cal.get("stayDurationSeconds") or {}).get("medianMinutes"),
                "warnings": self.cal.get("warnings"),
            }
        else:
            cal_prov = {
                "calibrated": False,
                "note": "Using the built-in hand-written demand curve and an "
                        "invented lognormal stay distribution. Supply "
                        "--calibration with a file derived from real "
                        "parking-event data to make these statistics measured "
                        "and citable.",
            }
        return {
            "simulator": SIMULATOR_ID,
            "version": "1.1.0",
            "seed": self.seed,
            "calibration": cal_prov,
            "timezoneAssumed": HOBART_TZ_NAME + " (fixed UTC+10 for determinism)",
            "simulatedNow": iso(self.sim_epoch),
            "wallClockUptimeSeconds": round(time.time() - self.started_wall, 1),
            "tickCount": self.tick_count,
            "bays": len(self.bays),
            "carparks": len(self.carparks),
            "disclaimer": DISCLAIMER,
            "separationNote": (
                "This simulator drives the AVAILABILITY lane only. The "
                "`restriction` property on each bay is inventory metadata "
                "carried so tests can assert that occupancy NEVER upgrades a "
                "legality verdict - per README 'Keep legality and availability "
                "separate'. A consumer must not map restriction -> ALLOWED/"
                "PROHIBITED. Those come from the deterministic rule kernel."
            ),
            "endpoints": ["/api/health", "/api/carparks.json", "/api/bays.geojson",
                          "/api/snapshot.json", "/api/bay/<bay_id>", "/stream",
                          "/api/meta.json"],
        }


def iso(epoch):
    if epoch is None:
        return None
    return datetime.fromtimestamp(epoch, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# --------------------------------------------------------------------------- #
# HTTP layer
# --------------------------------------------------------------------------- #

WORLD: World | None = None
CONFIG = {"tick": 15.0, "speed": 1.0}


class Handler(BaseHTTPRequestHandler):
    server_version = "PTE-Sim/1.0"
    protocol_version = "HTTP/1.1"

    def log_message(self, fmt, *args):
        pass  # keep stdout clean; the ticker prints its own summary

    def _send(self, code, body, ctype="application/json", extra=None):
        data = body if isinstance(body, bytes) else json.dumps(body).encode()
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(data)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-PTE-Synthetic", "true")
        for k, v in (extra or {}).items():
            self.send_header(k, v)
        self.end_headers()
        self.wfile.write(data)

    def do_GET(self):
        path = self.path.split("?")[0].rstrip("/") or "/"
        assert WORLD is not None
        try:
            if path in ("/", "/index.html"):
                self._send(200, WORLD.meta(), ctype="application/json")
            elif path == "/api/health":
                self._send(200, WORLD.source_health())
            elif path == "/api/carparks.json":
                self._send(200, WORLD.carparks_json())
            elif path == "/api/bays.geojson":
                self._send(200, WORLD.bays_geojson(),
                           ctype="application/geo+json")
            elif path == "/api/snapshot.json":
                self._send(200, WORLD.snapshot())
            elif path == "/api/meta.json":
                self._send(200, WORLD.meta())
            elif path.startswith("/api/bay/"):
                bay_id = path[len("/api/bay/"):]
                detail = WORLD.bay_detail(bay_id)
                if detail is None:
                    self._send(404, {"error": "unknown bayId", "bayId": bay_id,
                                     "synthetic": True})
                else:
                    self._send(200, detail)
            elif path in ("/stream", "/api/events/stream"):
                self._sse()
            elif path in ("/healthz", "/ready"):
                self._send(200, {"ok": True})
            else:
                self._send(404, {"error": "not found", "path": path,
                                 "see": "/api/meta.json"})
        except (BrokenPipeError, ConnectionResetError):
            pass

    def _sse(self):
        assert WORLD is not None
        self.send_response(200)
        self.send_header("Content-Type", "text/event-stream")
        self.send_header("Cache-Control", "no-store")
        self.send_header("Connection", "keep-alive")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("X-PTE-Synthetic", "true")
        self.end_headers()
        last_seq = WORLD.seq
        try:
            self.wfile.write(b"retry: 3000\n\n")
            self.wfile.flush()
            while True:
                time.sleep(0.4)
                with WORLD.lock:
                    new = [e for e in WORLD.events if e.get("seq", 0) > last_seq]
                if not new:
                    self.wfile.write(b": keepalive\n\n")
                    self.wfile.flush()
                    continue
                for e in new:
                    last_seq = e["seq"]
                    self.wfile.write(f"event: {e['type']}\n".encode())
                    self.wfile.write(b"data: " + json.dumps(e).encode() + b"\n\n")
                self.wfile.flush()
        except (BrokenPipeError, ConnectionResetError, OSError):
            return


def ticker():
    assert WORLD is not None
    interval = CONFIG["tick"]
    speed = CONFIG["speed"]
    next_report = time.time() + 10
    while True:
        t0 = time.time()
        events = WORLD.tick(interval * speed)
        if time.time() >= next_report:
            h = WORLD.source_health()
            m = h["metrics"]
            print(f"[sim] tick={WORLD.tick_count:>5} "
                  f"simTime={WORLD.local_dt().strftime('%a %H:%M:%S')} "
                  f"free={WORLD.snapshot()['onStreet']['free']:>4} "
                  f"occ={WORLD.snapshot()['onStreet']['occupied']:>4} "
                  f"unk={m['unknownStatusBays']:>3} "
                  f"state={h['state']} events_last_tick={len(events)}",
                  flush=True)
            next_report = time.time() + 10
        sleep_for = max(0.0, interval - (time.time() - t0))
        time.sleep(sleep_for)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--host", default="0.0.0.0",
                    help="bind address (default 0.0.0.0 so previews/proxies work)")
    ap.add_argument("--port", type=int, default=8090)
    ap.add_argument("--tick", type=float, default=15.0,
                    help="seconds between sensor ticks (Park My Ride publishes 15)")
    ap.add_argument("--speed", type=float, default=1.0,
                    help="simulated-time multiplier (20 = 20x faster than wall clock)")
    ap.add_argument("--seed", type=int, default=1337, help="RNG seed for reproducibility")
    ap.add_argument("--sim-start", default=None,
                    help="'HH:MM' local time to start at (today's date), or "
                         "'YYYY-MM-DDTHH:MM' to pin the date too. Pinning the "
                         "date matters: weekend multipliers and the Saturday "
                         "Salamanca market spike both depend on the weekday.")
    ap.add_argument("--bays-per-block", type=int, default=None,
                    help="override bay density per street block")
    ap.add_argument("--calibration", default=None,
                    help="calibration.json from tools/telemetry/calibrate_sim.py. "
                         "Replaces the hand-written demand curve and stay "
                         "distribution with ones measured from REAL parking-event "
                         "data, and cites the source SHA-256.")
    args = ap.parse_args()

    calibration = None
    if args.calibration:
        if not os.path.exists(args.calibration):
            raise SystemExit(f"no calibration file at {args.calibration}")
        with open(args.calibration) as fh:
            calibration = json.load(fh)
        if not calibration.get("usable"):
            print("[sim] WARNING: calibration is marked usable=false; falling "
                  "back to the built-in hand-written curve.", flush=True)

    global WORLD, CONFIG
    CONFIG = {"tick": args.tick, "speed": args.speed}

    start_epoch = None
    if args.sim_start:
        hobart = timezone(timedelta(hours=10))
        if "T" in args.sim_start or "-" in args.sim_start:
            when = datetime.strptime(args.sim_start.replace(" ", "T"),
                                     "%Y-%m-%dT%H:%M").replace(tzinfo=hobart)
        else:
            hh, mm = (int(x) for x in args.sim_start.split(":"))
            when = datetime.now(hobart).replace(hour=hh, minute=mm, second=0,
                                                microsecond=0)
        start_epoch = when.timestamp()

    WORLD = World(seed=args.seed, sim_start=start_epoch,
                  bays_per_block=(args.bays_per_block, args.bays_per_block)
                  if args.bays_per_block else None,
                  calibration=calibration)

    print("=" * 74)
    print("PTE REAL-TIME AVAILABILITY SIMULATOR  —  SYNTHETIC DATA, NOT REAL")
    print("=" * 74)
    print(f"  bays (synthetic geometry) : {len(WORLD.bays)}")
    print(f"  car parks (real capacities): {len(WORLD.carparks)}")
    print(f"  tick                      : {args.tick}s  (speed x{args.speed})")
    print(f"  seed                      : {args.seed}")
    print(f"  sim clock starts at       : {WORLD.local_dt().strftime('%Y-%m-%d (%a) %H:%M:%S')} UTC+10")
    if WORLD.cal:
        prov = WORLD.cal.get("provenance", {})
        print(f"  CALIBRATED ON REAL DATA   : {WORLD.cal.get('label')}")
        print(f"    source sha256           : {prov.get('sourceSha256')}")
        print(f"    rows / bays / dates     : {prov.get('rowsRead'):,} / "
              f"{prov.get('distinctBays'):,} / {prov.get('distinctArrivalDates')}")
        sd = WORLD.cal.get("stayDurationSeconds", {})
        print(f"    median stay (measured)  : {sd.get('medianMinutes')} min")
        w = WORLD.cal.get("warnings") or []
        if w:
            print(f"    calibration warnings    : {len(w)} (see calibration.json)")
    else:
        print("  CALIBRATED ON REAL DATA   : NO - using built-in hand-written "
              "curve (invented distribution)")
    print(f"  listening                 : http://{args.host}:{args.port}")
    print("  endpoints                 : /api/meta.json /api/health /api/bays.geojson")
    print("                              /api/carparks.json /api/snapshot.json /stream")
    print("-" * 74)
    print(DISCLAIMER)
    print("=" * 74, flush=True)

    threading.Thread(target=ticker, daemon=True).start()
    httpd = ThreadingHTTPServer((args.host, args.port), Handler)
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\n[sim] shutting down")


if __name__ == "__main__":
    main()
